# Generated by Django 4.2.7 on 2023-12-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_description_audio_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(default=8),
        ),
    ]
